name: expen
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+1
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  equatable: ^2.0.7
  flutter_material_pickers: ^3.7.0
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  fl_chart: ^0.70.2
  flutter_launcher_icons: ^0.14.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/wallet_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/wallet_icon.png"
  windows:
    generate: true
    image_path: "assets/icons/wallet_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/wallet_icon.png"
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700